# Regenerates lib/src/icons/lucide_icons.dart (the LucideIcons namespace) from
# the icon-definition sources. Run from the package root, then format:
#   perl tool/gen_lucide.pl lib/src/icons/gen/*.dart lib/src/icons/icon_registry.dart \
#     > lib/src/icons/lucide_icons.dart && dart format lib/src/icons/lucide_icons.dart
# (We extract from source rather than `dart run`, since the package needs Flutter.)
use strict; use warnings;
my @imports = qw(
  combo_icons.dart draw_icons.dart rotate_icons.dart scale_icons.dart
  stagger_icons.dart translate_icons.dart
);
push @imports, sprintf("gen/gen_%02d.dart", $_) for (1..20);
my %reserved = map {$_=>1} qw(assert break case catch class const continue
  default do else enum extends false final finally for if in is new null rethrow
  return super switch this throw true try var void while with dynamic await yield);
my (%seen, @members);
local $/; # slurp
for my $f (@ARGV) {
  open my $fh, '<', $f or die $!;
  my $src = <$fh>; close $fh;
  while ($src =~ /\bIconEntry\(\s*'([^']+)'\s*,\s*(k\w+Icon)/g) {
    my ($name, $const) = ($1, $2);
    my $m = $name;
    $m =~ s/-/_/g;           # snake_case: bittensor-evm -> bittensor_evm
    $m = "icon_$m" if $m =~ /^[0-9]/;
    $m .= "_" if $reserved{$m};
    next if $seen{$m}++;
    push @members, "  static const $m = $const;";
  }
}
my $out = "// GENERATED by tool/gen_lucide.pl — do not edit by hand.\n";
$out .= "// ignore_for_file: constant_identifier_names\n";
$out .= "//\n// Namespaced accessors for the full Lucide stroke set.\n\n";
$out .= "import '$_';\n" for @imports;
$out .= "\n/// Namespaced Lucide stroke icons — `LucideIcons.bell`,\n";
$out .= "/// `LucideIcons.arrow_down`, … Mirrors Flutter's `Icons` convention.\n";
$out .= "abstract final class LucideIcons {\n";
$out .= join("\n", @members) . "\n}\n";
print $out;
